"""Response models for LLM calls (transport-agnostic)."""

from __future__ import annotations

from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    """Result of a single LLM call.

    Captures success/failure, generated content, token usage, and timing in a
    shape that does not depend on any specific provider SDK. Each provider
    wrapper (e.g. :class:`berb_common.anthropic.AnthropicClient`) returns this
    type so call-sites can stay provider-neutral.

    Attributes:
        success: True if the call returned a usable response.
        status_code: HTTP-style status code (0 when no HTTP exchange occurred).
        content: Generated text (assembled across all text blocks).
        error_message: Human-readable failure message; empty on success.
        input_tokens: Tokens consumed by the prompt.
        output_tokens: Tokens generated by the model.
        stop_reason: Provider-specific stop reason (e.g. ``"end_turn"``).
        model: Model identifier as reported by the provider.
        duration_seconds: Wall-clock time for the request.

    Example:
        >>> r = LLMResponse(success=True, content="Hello", input_tokens=5, output_tokens=2)
        >>> r.total_tokens
        7
    """

    success: bool = False
    status_code: int = 0
    content: str = ""
    error_message: str = ""
    input_tokens: int = 0
    output_tokens: int = 0
    stop_reason: str = ""
    model: str = ""
    duration_seconds: float = Field(0.0, description="Wall-clock seconds for the request")

    @property
    def total_tokens(self) -> int:
        """Sum of input and output tokens."""
        return self.input_tokens + self.output_tokens
