name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: berb223/BERB-workflows/.github/workflows/python-ci.yml@v1
    with:
      mypy-path: src/berb_common
